ai_app/urls.py
from django.contrib import admin
from django.urls import path, include
#import predictions.views as prediction

urlpatterns = [
    path('', include('predictions.urls')),
    path('admin/', admin.site.urls),
]

predictions/urls.py
from django.urls import path
from . import views

app_name = 'predictions'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('predict/', views.predict_home, name='predict_home'),
    path('predict/result/', views.predict, name='predict'),
    path('tracking/', views.tracking_ship, name='search'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('top/', views.Top.as_view(), name='top'),
    path('user_detail/<int:pk>/', views.User_detail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.User_update.as_view(), name='user_update'),
    path('user_create/', views.User_create.as_view(), name='user_create'),
    path('user_create/done', views.User_create_done.as_view(),
         name='user_create_done'),
    path('user_create/complete/<token>/',
         views.User_create_complete.as_view(), name='user_create_complete'),
    path('calendar/', views.MonthCalendar.as_view(), name='month'),
    path('calendar/month/<int:year>/<int:month>/',
         views.MonthCalendar.as_view(), name='month'),
    path('calendar/week/', views.WeekCalendar.as_view(), name='week'),
    path('calendar/week/<int:year>/<int:month>/<int:day>/',
         views.WeekCalendar.as_view(), name='week'),
    path('calendar/week_with_schedule/', views.WeekWithScheduleCalendar.as_view(),
         name='week_with_schedule'),
    path('calendar/week_with_schedule/<int:year>/<int:month>/<int:day>/',
         views.WeekWithScheduleCalendar.as_view(),
         name='week_with_schedule'
         ),
    path('calendar/month_with_schedule/',
         views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
         ),
    path('calendar/month_with_schedule/<int:year>/<int:month>/',
         views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
         ),
    path('calendar/mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path('calendar/mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(),
         name='mycalendar'
         ),
    path('calendar/month_with_forms/',
         views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
         ),
    path('calendar/month_with_forms/<int:year>/<int:month>/',
         views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
         ),

]

predictions/models.py
import datetime
from django.utils import timezone
from django.db import models
from tensorflow import keras
from keras.models import load_model
from PIL import Image
import numpy as np
import tensorflow as tf
import io
import base64


#graph = tf.get_default_graph()
graph = tf.compat.v1.get_default_graph()  # こっち使えって


class Photo(models.Model):
    image = models.ImageField(upload_to='photos')
    IMAGE_SIZE = 224  # 画像サイズ
    MODEL_FILE_PATH = 'predictions/ml_models/vgg16_transfer.h5'  # モデルファイル
    classes = ['car', 'motorbike']
    num_classes = len(classes)

    def predict(self):
        model = None
        global graph
        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)  # バイナリーデータに変換

            image = Image.open(img_bin)  # 変換後渡す＝標準入力と同じ動作
            image = image.convert('RGB').resize(
                (self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image) / 255.0  # 浮動小数点で正規化
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)

            return self.classes[predicted], percentage

    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return 'data:' + img.file.content_type + ';base64,' + base64_img


class Schedule(models.Model):
    """スケジュール"""
    summary = models.CharField('概要', max_length=100)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(23, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

predictions/views.py
import datetime
from . import mixins
from django.shortcuts import redirect, render
from django.views import generic
from django.views.generic import CreateView
from django.conf import settings
from django.http import HttpResponse, Http404, HttpResponseBadRequest
from django.template import loader
from django.template.loader import render_to_string
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.decorators import login_required  # 関数用
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin  # クラス用
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from .forms import Photo_form, Login_form, User_update_form, User_create_form
from .models import Photo
from .models import Schedule
from .search import scraping, target
from .forms import BS4ScheduleForm, SimpleScheduleForm
import jaconv  # mojimojiの代わり
import re

# class ~~(LoginRequiredMixin,~~ )
@login_required
def predict_home(request):
    # index
    template = loader.get_template('predictions/predict_home.html')
    context = {'form': Photo_form()}
    return HttpResponse(template.render(context, request))


def predict(request):
    # リザルト表示
    if not request.method == 'POST':
        return redirect('predictions:predict_home')

    form = Photo_form(request.POST, request.FILES)

    if not form.is_valid():
        raise ValueError('invalid form')

    photo = Photo(image=form.cleaned_data['image'])
    predict_label, percentage = photo.predict()
    template = loader.get_template('predictions/result.html')
    context = {
        'image_name': photo.image.name,
        'image_data': photo.image_src(),
        'class_label': predict_label,
        'score': percentage,
    }
    return HttpResponse(template.render(context, request))


def tracking_ship(request):
    track_number = request.GET.get('track_number')
    try:
        if 9 < len(track_number) < 20:  # 10桁以上20桁未満で通す
            track_number = jaconv.z2h(
                track_number, digit=True, ascii=True)  # 全角を半角に
            track_number = re.sub("\\D", "", track_number)  # 数字以外を消す
            texts = scraping(track_number)  # 追跡番号検索
            data_dict = {}  # データ用
            data = {'track_number': str(track_number)}
            for t in target:  # 一度取得データをdictで整形
                data_dict.update([(t, texts[t])])
            target_dict = {  # ターゲット一覧
                target[0]: "日本郵政",
                target[1]: "佐川急便",
                target[2]: "クロネコヤマト",
                target[3]: "西濃運輸",
                target[4]: "日本通運",
                target[5]: "福山通運",
            }
            target_td_num = {
                target[0]: 6,
                target[1]: 8,
                target[2]: 6,
                target[3]: 3,
                target[4]: 5,
                target[5]: 2,
            }
            # for i in range(len(target)):
            #   target_td_num.update([(
            #        target[i], int((len(data_dict[target[i]]))/2)
            #    )])

            data.update([('data', data_dict)])  # 扱いやすい様辞書の入れ子にする
            data.update([('targets', target_dict)])  # ターゲット一覧
            data.update([('td_num', target_td_num)])  # ターゲットのtd数
            # print(data)
            return render(request, 'predictions/search.html', data)
        else:
            return render(request, 'predictions/search.html')
    except:
        return render(request, 'predictions/search.html')


class Index(generic.TemplateView):
    template_name = 'predictions/index.html'


class Top(generic.TemplateView):
    template_name = 'predictions/top.html'


class Login(LoginView):
    # ログイン
    form_class = Login_form
    template_name = 'predictions/login.html'

    # def get_success_url(self):
    #    url = self.get_redirect_url()
    #    return url or resolve_url('predictions:predict', pk=self.request.user.pk)


class Logout(LogoutView):
    # ログアウト
    template_name = 'predictions/top.html'

    def log_out(self):
        logout(self.request)


User = get_user_model()


class User_detail(generic.DetailView):
    # ユーザ情報閲覧
    model = User
    template_name = 'predictions/user_detail.html'


class User_update(generic.UpdateView):
    # ユーザ情報更新
    model = User
    form_class = User_update_form
    template_name = 'predictions/user_update.html'

    def get_success_url(self):
        return resolve_url('predictions:user_detail', pk=self.kwargs['pk'])


class User_create(generic.CreateView):
    # ユーザ仮登録
    template_name = 'predictions/user_create.html'
    form_class = User_create_form

    def form_valid(self, form):
        # 仮登録と本登録用メールの発行.
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単
        # 退会処理も、is_activeをFalseにするだけ
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string(
            'mail_templates/subject.txt', context)
        message = render_to_string(
            'mail_templates/message.txt', context)

        user.email_user(subject, message)
        return redirect('predictions:user_create_done')


class User_create_done(generic.TemplateView):
    # ユーザ仮登録
    template_name = 'predictions/user_create_done.html'


class User_create_complete(generic.TemplateView):
    # メール内URLアクセス後のユーザ本登録
    template_name = 'predictions/user_create_complete.html'
    timeout_seconds = getattr(
        settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        # tokenが正しければ本登録.
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class MonthCalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'predictions/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class WeekCalendar(mixins.WeekCalendarMixin, generic.TemplateView):
    """週間カレンダーを表示するビュー"""
    template_name = 'predictions/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


class WeekWithScheduleCalendar(mixins.WeekWithScheduleMixin, generic.TemplateView):
    """スケジュール付きの週間カレンダーを表示するビュー"""
    template_name = 'predictions/week_with_schedule.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


class MonthWithScheduleCalendar(mixins.MonthWithScheduleMixin, generic.TemplateView):
    """スケジュール付きの月間カレンダーを表示するビュー"""
    template_name = 'predictions/month_with_schedule.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""
    template_name = 'predictions/mycalendar.html'
    model = Schedule
    date_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(
                year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('predictions:mycalendar', year=date.year, month=date.month, day=date.day)


class MonthWithFormsCalendar(mixins.MonthWithFormsMixin, generic.View):
    """フォーム付きの月間カレンダーを表示するビュー"""
    template_name = 'predictions/month_with_forms.html'
    model = Schedule
    date_field = 'date'
    form_class = SimpleScheduleForm

    def get(self, request, **kwargs):
        context = self.get_month_calendar()
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        context = self.get_month_calendar()

predictions/templates/predictions/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    {%load static%} {%load bootstrap4%} {%bootstrap_css%}
    <link rel="stylesheet" type="text/css" href="{%static 'predictions/css/style.css'%}" />
    {%bootstrap_javascript jquery='full'%}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{%block title%}{%endblock%}</title>
  </head>
  <body>
    <nav class="navbar navbar-extend-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'predictions:index' %}">
      {%block top_title%}Track&Predict{%endblock%}</a>
      {% if request.path == '/tracking/'%}
        <a class="nav-item nav-link" href="{% url 'predictions:predict_home'%}">バイク・車推定</a>
        <a> or </a>
        <a class="nav-item nav-link" href="{% url 'predictions:month'%}">カレンダー</a>
      {%elif request.path == '/predict/'%}
        <a class="nav-item nav-link" href="{% url 'predictions:search'%}">追跡番号一括検索くん</a>
        <a> or </a>
        <a class="nav-item nav-link" href="{% url 'predictions:month'%}">カレンダー</a>
      {%elif 'calendar' in request.path %}
        <a class="nav-item nav-link" href="{% url 'predictions:search'%}">追跡番号一括検索くん</a>
        <a> or </a>
        <a class="nav-item nav-link" href="{% url 'predictions:predict_home'%}">バイク・車推定</a>
      {%endif%}
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index'%}">管理サイト</a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
                {% if request.path == '/tracking/'%}
                    <a class="nav-item nav-link" href="{% url 'predictions:predict_home'%}">バイク・車推定</a>
                    <a> or </a>
                    <a class="nav-item nav-link" href="{% url 'predictions:month'%}">カレンダー</a>
                {%elif request.path == '/predict/'%}
                    <a class="nav-item nav-link" href="{% url 'predictions:search'%}">追跡番号一括検索くん</a>
                    <a> or </a>
                    <a class="nav-item nav-link" href="{% url 'predictions:month'%}">カレンダー</a>
                {%elif 'calendar' in request.path %}
                    <a class="nav-item nav-link" href="{% url 'predictions:search'%}">追跡番号一括検索くん</a>
                    <a> or </a>
                    <a class="nav-item nav-link" href="{% url 'predictions:predict_home'%}">バイク・車推定</a>
                {%endif%}
                <a class="nav-item nav-link" href="{% url 'predictions:user_detail' user.pk %}">ユーザー情報閲覧</a>
                <a class="nav-item nav-link" href="{% url 'predictions:user_update' user.pk %}">ユーザー情報更新</a>
                <a style="float: left" class="nav-link" href="{% url 'predictions:logout'%}">Hi! {{request.user}} Logout?</a>
                <!-- <a style="float:right" class="nav-item" >Now {{request.user.pk}} users active. </a> -->
                {% else %}
                <a class="nav-link" href="{% url 'predictions:login'%}">Welcome! please <b>Login</b></a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
        {%if 'calendar' in request.path %}
            {% include 'predictions/includes/tags.html' %}
        {%endif%}
        {%block content%}{%endblock%}
    </div>
  </body>
</html>

predictions/templates/predictions/index.html
{% extends "predictions/base.html" %}
{%block title%}Home{%endblock%}
{%block top_title%}Track&Predict{%endblock%}
{%block content%}

<a href="{%url 'predictions:predict_home'%}" class='btn btn-success'>バイク車判定</a> 
<a href="{%url 'predictions:search'%}" class='btn btn-primary'>追跡番号検索くん</a> 

{% endblock%}

predictions/templates/predictions/login.html
{% extends "predictions/base.html" %}
{%block title%}Login Page{%endblock%}
{%block top_title%}Login form{%endblock%}
{% block content %}
<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
                <br>
                <a href="{%url 'predictions:user_create'%}" class='btn btn-primary btn-lg btn-block'>新規登録はこちら</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

predictions/templates/predictions/month_with_forms.html
{% extends 'predictions/base.html' %} 
{%block title%}Calendar{%endblock%}
{%block top_title%}Calendar6{%endblock%}
{% block content %}
<style>
  table {
    table-layout: fixed;
  }
</style>

<a href="{% url 'predictions:month_with_forms' month_previous.year month_previous.month %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'predictions:month_with_forms' month_next.year month_next.month %}">次月</a>

<form action="" method="POST">
  {{ month_formset.management_form }}
  <table class="table">
    <thead>
      <tr>
        {% for w in week_names %}
        <th>{{ w }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
      {% for week_day_forms in month_day_forms %}
        <tr>
        {% for day, forms in week_day_forms.items %}
          {% if now == day %}
            <td class="table-success">
          {% else %}
            </td>
            <td>
          {% endif %}
          <div>
          {% if month_current.month != day.month %}
            {{ day | date:"m/d" }}
          {% else %}
            {{ day.day }}
          {% endif %}
          {% for form in forms %}
            {{ form.as_p }}
          {% endfor %}
          </div>
          </td>
        {% endfor %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">送信</button>
</form>
{% endblock %}

predictions/templates/predictions/month_with_schedule.html
{% extends 'predictions/base.html' %}
{%block title%}Calendar{%endblock%}
{%block top_title%}Calendar3{%endblock%}
{% block content %}
<style>
  table {
    table-layout: fixed;
  }
  td > div {
    height: 100px;
    overflow: hidden;
    white-space: nowrap;
  }
</style>
<a href="{% url 'predictions:month_with_schedule' month_previous.year month_previous.month %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'predictions:month_with_schedule' month_next.year month_next.month %}">次月</a>

<table class="table">
  <thead>
    <tr>
      {% for w in week_names %}
      <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for week_day_schedles in month_day_schedules %}
    <tr>
      {% for day, schedules in week_day_schedles.items %}
      {% if now == day %}
      <td class="table-success">
      {% else %}
      </td>
      <td>
      {% endif %}
        <div>
          {% if month_current.month != day.month %}
            {{ day | date:"m/d" }}
          {% else %}
            {{ day.day }}
          {% endif %}
          {% for schedule in schedules %}
          <p>aaaaaa{{ schedule.summary }}</p><!--スケジュール該当箇所-->
          {% endfor %}
        </div>
      </td>
      {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

predictions/templates/predictions/mycalendar.html
{% extends 'predictions/base.html' %}
{%block title%}Calendar{%endblock%}
{%block top_title%}Calendar5{%endblock%}
{% block content %}
<div class="row">
  <div class="col-md-3">
    {% include 'predictions/includes/month.html' %}
    <hr />
    <form action="" method="POST">
      {{ form.non_field_errors }}
      {% for field in form %}
        <div class="form-group row">
          <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
          <div class="col-sm-8">{{ field }} {{ field.errors }}</div>
        </div>
      {% endfor %} {% csrf_token %}
      <button type="submit" class="btn btn-primary btn-block">送信</button>
    </form>
  </div>
  <div class="col-md-9">{% include 'predictions/includes/week.html' %}</div>
</div>
{% endblock %} 

{% block extrajs %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
<script>
  $(function () {
    // timedropper
    $("#id_start_time").timeDropper({
      format: "H:mm",
      setCurrentTime: false,
    });
    $("#id_end_time").timeDropper({
      format: "H:mm",
      setCurrentTime: false,
    });
  });
</script>
{% endblock %}

predictions/templates/predictions/top.html
{% extends "predictions/base.html" %}
{%block title%}Top{%endblock%}
{%block top_title%}Top page{%endblock%}
{%block content%}

<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <a href="{%url 'predictions:login'%}" class='btn btn-success'>ログインしてね！</a> 
                <a href="{%url 'predictions:user_create'%}" class='btn btn-primary'>新規登録はこちら</a> 
            </div>
        </div>
    </div>
</form>
{% endblock%}

predictions/templates/predictions/user_create.html
{% extends "predictions/base.html" %}
{%block title%}Sign up{%endblock%}
{%block top_title%}新規登録{%endblock%}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
    <a href="{%url 'predictions:login'%}" class='btn btn-success btn-lg'>登録済み？</a> 
</form>
{% endblock %}

predictions/templates/predictions/user_create_complete.html
{% extends "predictions/base.html" %}
{%block title%}Welcome!{%endblock%}
{%block top_title%}本登録完了{%endblock%}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'predictions:login' %}">ログイン</a>
</p>
{% endblock %}

predictions/templates/predictions/user_create_done.html
{% extends "predictions/base.html" %}
{%block title%}Sign up{%endblock%}
{%block top_title%}仮登録完了{%endblock%}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
    メールが届かない場合は、メールアドレスに間違いがある可能性があります。再度登録をお願いします。
</p>
 <a class="btn btn-primary btn-lg" href="{% url 'predictions:login' %}">ログインページ</a>
{% endblock %}

predictions/templates/predictions/user_update.html
{% extends "predictions/base.html" %}
{%block title%}Update details{%endblock%}
{%block top_title%}{{ user.username }}のユーザ情報更新ページ{%endblock%}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg" >送信</button>
    <a href="{%url 'predictions:index'%}" class="btn btn-primary btn-lg">戻る</a>
</form>
{% endblock %}

predictions/templates/predictions/week.html
{% extends 'predictions/base.html' %}
{%block title%}Calendar{%endblock%}
{%block top_title%}Calendar2{%endblock%}
{% block content %}

<a href="{% url 'predictions:week' week_previous.year week_previous.month  week_previous.day %}">前週</a>
{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
<a href="{% url 'predictions:week' week_next.year week_next.month  week_next.day %}">次週</a>

<table class="table">
  <thead>
    <tr>
      {% for w in week_names %}
      <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for day in week_days %} {% if now == day %}
      <td class="table-success">{% else %}</td>

      <td>{% endif %} {% if week_first.month != day.month %} {{ day | date:"m/d" }} {% else %} {{ day.day }} {% endif %}</td>
      {% endfor %}
    </tr>
  </tbody>
</table>
{% endblock %}